{
 "title": "LOCKSS network monitor",
 "tags": [ "main" ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "LOCKSS network dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total archive size",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT tdb_publisher, SUM (AUsize) AS AU_size from (SELECT name, tdb_publisher, MAX(content_size) as AUsize\nFROM plnmonitor.au_current GROUP BY name, tdb_publisher) AS TDB GROUP BY tdb_publisher"
    }
   ]
  },
  {
   "title": "Active Boxes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(box,$__interval),\n  count(id) AS \"id\"\nFROM lockss_box_info\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Active AUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  max(active_aus)\nFROM plnmonitor.lockss_box_data_current\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg copies/AU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with nbcopies as (select name, SUM(recent_poll_agreement) from plnmonitor.au_current  GROUP BY 1 ORDER BY 1)  select (AVG(sum)) from nbcopies "
    }
   ]
  },
  {
   "title": "Average poll agreement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(recent_poll_agreement) from plnmonitor.au_current"
    }
   ]
  },
  {
   "title": "Last completed poll",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(last_completed_poll)\nFROM plnmonitor.au_current\n"
    }
   ]
  },
  {
   "title": "Min. free capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  min(free) AS \"free\"\nFROM lockss_box_data_version\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LOCKSS Network map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  lockss_box_info.name AS shortname,\n  latitude,\n  longitude,\n  lockss_box_data_current.active_aus\nFROM plnmonitor.lockss_box_info\nINNER JOIN plnmonitor.lockss_box_data_current ON lockss_box_info.box=lockss_box_data_current.box\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Archival Units per publisher",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * from plnmonitor.content_per_tdb_publisher"
    }
   ]
  },
  {
   "title": "Maximum time since last completed poll ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  min (extract(epoch from updated_at)*1000 - last_completed_poll) AS \"last completed poll avg\"\nFROM plnmonitor.au_version\nWHERE\n  $__timeFilter(updated_at) \nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LOCKSS boxes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  lockss_box_info.name as \"LOCKSS box name\",\n  MAX(lockss_box.ipaddress) as \"IP address\",\n  MAX(lockss_box_info.country) as \"Country\",\n  MAX(SPLIT_PART((SUBSTRING(lockss_box.daemon_full_version::text FROM 35 for 7)), ',', 1)) as \"Daemon version\",\n  SUM(lockss_box_data_current.active_aus) as \"Active AUs\",\n  MIN(created_at) as \"Active since\",\n  MAX(SPLIT_PART(SPLIT_PART(lockss_box.platform::text,'=',2), ',', 1)) as \"Platform\",\n  MAX(SPLIT_PART(SPLIT_PART(lockss_box.java_version::text,'=',2), ',', 1)) as \"Java version\"\nFROM plnmonitor.lockss_box_info INNER JOIN plnmonitor.lockss_box_data_current on lockss_box_info.box=lockss_box_data_current.box\nINNER JOIN plnmonitor.lockss_box on lockss_box.id = lockss_box_info.box\nGROUP BY lockss_box_info.name\nORDER BY lockss_box_info.name\n"
    }
   ]
  },
  {
   "title": "AU status across the network",
   "type": "table",
   "gridPos": { "h": 39, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "rawSql": "PIVOTRAWSQLREQUEST" }
   ]
  },
  {
   "title": "Archival Units Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name AS AU_name,\n  MAX(content_size) AS size,\n  MIN(creation_time) AS ingested_by_network_on,\n  MAX(recent_poll_agreement) AS recent_poll_agreement,\n  MAX(disk_usage) AS Disk_usage,\n  MIN(last_crawl) AS Last_crawl,\n  min(last_poll_result) AS last_poll_result,\n  MAX(last_completed_poll) AS Last_completed_poll,\n  MAX(plugin_name) AS plugin_name,\n  MAX(au_lockss_id) AS au_lockss_id\nFROM plnmonitor.au_current\nGROUP BY name\nORDER BY name"
    }
   ]
  },
  {
   "title": "Peers ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "select lockss_box_info.name as \"Box name\", lockss_box.ipaddress as \"Box IP address\", peer_lockss_id as \"Peer IP address\", polls_rejected * 1.0 / (NULLIF(invitation_count,0) * 1.0) as \"polls rejection ratio\", last_message as \"last message received from peer\", invitation_count as \"#invitations sent to peer\", message_count as \"#messages from peer\",  polls_called as \"#polls called by peer\", polls_rejected as \"#polls rejected by peer\",  last_vote as \"last time peer voted\", last_poll as \"last participation in a poll from peer\", last_invitation as \"last time peer was invited in poll\", votes_cast as \"#votes casted by peer\"  from plnmonitor.peer INNER JOIN plnmonitor.lockss_box on lockss_box.id = peer.box INNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = peer.box where REGEXP_REPLACE(peer_lockss_id, '(TCP:\\[|]:9\\d+)', '', 'g')  in (select ipaddress from plnmonitor.lockss_box ) order by peer.box;"
    }
   ]
  },
  {
   "title": "Organizational and technical managers",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\n  institution.shortname as \"Location\",\n  lockss_box_info.box,\n  lockss_box_info.organizational_manager,\n  lockss_box_info.technical_manager,\n  CONCAT(person.first_name, ' ', person.name) as \"Name\",\n  person.email_address as \"Email\",\n  lockss_box_info.username,\n  lockss_box_info.country,\n  lockss_box_info.institution\n\n\nFROM plnmonitor.lockss_box_info\nINNER JOIN plnmonitor.person ON technical_manager=person.id or organizational_manager=person.id\nINNER JOIN plnmonitor.institution ON lockss_box_info.institution=institution.id"
    }
   ]
  }
 ]
}