{
 "title": "LOCKSS_BOX_NAME box",
 "tags": [ "box" ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "LOCKSS_BOX_NAME Box data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total archive size",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT tdb_publisher, SUM (AUsize) AS AU_size from (SELECT au_current.name, tdb_publisher, MAX(content_size) as AUsize\nFROM plnmonitor.au_current INNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box=au_current.box\nWHERE lockss_box_info.name = 'LOCKSS_BOX_NAME' GROUP BY au_current.name, tdb_publisher) AS TDB GROUP BY tdb_publisher"
    }
   ]
  },
  {
   "title": "Active AUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  name, active_aus\nFROM plnmonitor.lockss_box_data_current INNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box=lockss_box_data_current.box where name='LOCKSS_BOX_NAME'"
    }
   ]
  },
  {
   "title": "Average poll agreement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT lockss_box_info.name, avg(recent_poll_agreement) FROM plnmonitor.lockss_box_info INNER JOIN plnmonitor.au_current ON lockss_box_info.box=au_current.box  where lockss_box_info.name='LOCKSS_BOX_NAME' group by lockss_box_info.name;"
    }
   ]
  },
  {
   "title": "Last completed poll",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT lockss_box_info.name, MAX(last_completed_poll) FROM plnmonitor.lockss_box_info INNER JOIN plnmonitor.au_current ON lockss_box_info.box=au_current.box  where lockss_box_info.name='LOCKSS_BOX_NAME' group by lockss_box_info.name;"
    }
   ]
  },
  {
   "title": "Last completed poll",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT lockss_box_info.name,  MAX(last_completed_crawl) FROM plnmonitor.lockss_box_info INNER JOIN plnmonitor.au_current ON lockss_box_info.box=au_current.box  where lockss_box_info.name='LOCKSS_BOX_NAME' group by lockss_box_info.name;"
    }
   ]
  },
  {
   "title": "Min. free capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  min(free) AS \"free\"\nFROM plnmonitor.lockss_box_data_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_data_version.box = lockss_box_info.box\nWHERE\n  $__timeFilter(updated_at) AND\n  lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LOCKSS Box location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  lockss_box_info.name AS shortname,\n  latitude,\n  longitude,\n  lockss_box_data_current.active_aus\nFROM plnmonitor.lockss_box_info\nINNER JOIN plnmonitor.lockss_box_data_current ON lockss_box_info.box=lockss_box_data_current.box\nWHERE name='LOCKSS_BOX_NAME'\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Maximum time since last completed poll ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  min (extract(epoch from updated_at)*1000 - last_completed_poll) AS \"last completed poll avg\"\nFROM plnmonitor.au_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = au_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maximum time since last completed crawl ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  min (extract(epoch from updated_at)*1000 - last_completed_crawl) AS \"last completed crawl avg\"\nFROM plnmonitor.au_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = au_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Box used space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  max(size)  AS \"box size\",\n  max(used)  AS \"box used space\"\nFROM plnmonitor.lockss_box_data_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = lockss_box_data_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Box free space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  max(free)  AS \"box free space\"\nFROM plnmonitor.lockss_box_data_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = lockss_box_data_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Active AUs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  max(active_aus)  AS \"active AUs\"\nFROM plnmonitor.lockss_box_data_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = lockss_box_data_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Orphaned AUs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  max(orphaned_aus)  AS \"orphaned AUs\"\nFROM plnmonitor.lockss_box_data_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = lockss_box_data_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Deleted AUs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,$__interval),\n  max(deleted_aus)  AS \"deleted AUs\"\nFROM plnmonitor.lockss_box_data_version\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = lockss_box_data_version.box\nWHERE\n  $__timeFilter(updated_at) and lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LOCKSS box information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  lockss_box_info.name as \"LOCKSS box name\",\n  (lockss_box.ipaddress) as \"IP address\",\n  (lockss_box_info.country) as \"Country\",\n  (SPLIT_PART((SUBSTRING(lockss_box.daemon_full_version::text FROM 35 for 7)), ',', 1)) as \"Daemon version\",\n  (lockss_box_data_current.active_aus) as \"Active AUs\",\n  (created_at) as \"Active since\",\n  (SPLIT_PART(SPLIT_PART(lockss_box.platform::text,'=',2), ',', 1)) as \"Platform\",\n  (SPLIT_PART(SPLIT_PART(lockss_box.java_version::text,'=',2), ',', 1)) as \"Java version\"\nFROM plnmonitor.lockss_box_info INNER JOIN plnmonitor.lockss_box_data_current on lockss_box_info.box=lockss_box_data_current.box\nINNER JOIN plnmonitor.lockss_box on lockss_box.id = lockss_box_info.box\nWHERE name='LOCKSS_BOX_NAME'\n"
    }
   ]
  },
  {
   "title": "Organizational and technical managers",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\n  institution.shortname as \"Location\",\n  lockss_box_info.box,\n  lockss_box_info.name,\n  lockss_box_info.organizational_manager,\n  lockss_box_info.technical_manager,\n  CONCAT(person.first_name, ' ', person.name) as \"Name\",\n  person.email_address as \"Email\",\n  lockss_box_info.username,\n  lockss_box_info.country,\n  lockss_box_info.institution\n\n\nFROM plnmonitor.lockss_box_info\nINNER JOIN plnmonitor.person ON technical_manager=person.id or organizational_manager=person.id\nINNER JOIN plnmonitor.institution ON lockss_box_info.institution=institution.id\nWHERE lockss_box_info.name = 'LOCKSS_BOX_NAME'"
    }
   ]
  },
  {
   "title": "Archival Units Details for LOCKSS box LOCKSS_BOX_NAME",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  au_current.name AS AU_name,\n  MAX(content_size) AS size,\n  MIN(creation_time) AS ingested_by_network_on,\n  MAX(recent_poll_agreement) AS recent_poll_agreement,\n  MAX(disk_usage) AS Disk_usage,\n  MIN(last_crawl) AS Last_crawl,\n  min(last_poll_result) AS last_poll_result,\n  MAX(last_completed_poll) AS Last_completed_poll,\n  MAX(plugin_name) AS plugin_name,\n  MAX(au_lockss_id) AS au_lockss_id\nFROM plnmonitor.au_current\nINNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box=au_current.box\nWHERE lockss_box_info.name = 'LOCKSS_BOX_NAME'\nGROUP BY au_current.name\nORDER BY au_current.name"
    }
   ]
  },
  {
   "title": "Peers of LOCKSS box LOCKSS_BOX_NAME",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "select lockss_box_info.name as \"Box name\", lockss_box.ipaddress as \"Box IP address\", peer_lockss_id as \"Peer IP address\", polls_rejected * 1.0 / (NULLIF(invitation_count,0) * 1.0) as \"polls rejection ratio\", last_message as \"last message received from peer\", invitation_count as \"#invitations sent to peer\", message_count as \"#messages from plnmonitor.peer\",  polls_called as \"#polls called by peer\", polls_rejected as \"#polls rejected by peer\",  last_vote as \"last time peer voted\", last_poll as \"last participation in a poll from peer\", last_invitation as \"last time peer was invited in poll\", votes_cast as \"#votes casted by peer\"  from plnmonitor.peer INNER JOIN plnmonitor.lockss_box on lockss_box.id = peer.box INNER JOIN plnmonitor.lockss_box_info on lockss_box_info.box = peer.box where REGEXP_REPLACE(peer_lockss_id, '(TCP:\\[|]:9\\d+)', '', 'g')  in (select ipaddress from plnmonitor.lockss_box ) AND lockss_box_info.name ='LOCKSS_BOX_NAME' order by peer.box;"
    }
   ]
  },
  { "title": "Log files", "type": "logs", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 } }
 ]
}